" Vi IMproved
set nocompatible

" Backspace 
set backspace=indent,eol,start 

" sets up pathogen
execute pathogen#infect()

" sets up syntax highlighting
syntax enable

" sets line numbers
set relativenumber number

" sets parenthetical highlighting to just bold
hi MatchParen cterm=bold ctermbg=Gray ctermfg=none

" sets tabs to 4 spaces
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab

" makes indenting smart
set smartindent

" sets noexpandtab for Makefiles
if &ft == 'make'
    setlocal noexpandtab
    setlocal tabstop=4
endif

" enables plugins
filetype plugin on

" sets diff cursors for modes
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_SR = "\<Esc>]50;CursorShape=2\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"

" sets ctrl-h to toggle line numbers
nnoremap <C-h> :set number! relativenumber! <CR>

" makes ctrl-l clear search highlighting
nnoremap <silent> <C-l> :nohlsearch<CR><C-l>

" makes lightline work
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ }
set noshowmode

" makes syntastic behave
let g:syntastic_python_checkers = ['flake8']
let g:syntastic_check_on_wq = 0
let g:syntastic_check_on_open = 1

" Ultisnips
let g:UltiSnipsUsePythonVersion = 3
let g:UltiSnipsExpandTrigger = '<C-j>'
let g:UltiSnipsJumpForwardTrigger = '<C-j>'
let g:UltiSnipsJumpBackwardTrigger = '<C-k>'

" YCM
let g:ycm_server_python_interpreter = systemlist("which python2.7")[0]
let g:ycm_autoclose_preview_window_after_insertion = 1

" makes cmd-v paste correctly
inoremap <D-v> <ESC>:set paste<CR>"*p<ESC>:set nopaste<CR>
